// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaeIkmBy5t2rZHag8tmWwrrUCv0rf4LLM',
    appId: '1:774583050669:web:9d8772b104310765368124',
    messagingSenderId: '774583050669',
    projectId: 'food-ap-2eeb8',
    authDomain: 'food-ap-2eeb8.firebaseapp.com',
    storageBucket: 'food-ap-2eeb8.firebasestorage.app',
    measurementId: 'G-Y75R3XWZ5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxmlBrj2f3HlIrRJCUEEIpUiEPCXGtCc',
    appId: '1:774583050669:android:cb733e84257e6391368124',
    messagingSenderId: '774583050669',
    projectId: 'food-ap-2eeb8',
    storageBucket: 'food-ap-2eeb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMjfLwdlgM0C5LS22gV_7rVuOpaTXf6aI',
    appId: '1:774583050669:ios:11887cb33c330edc368124',
    messagingSenderId: '774583050669',
    projectId: 'food-ap-2eeb8',
    storageBucket: 'food-ap-2eeb8.firebasestorage.app',
    iosBundleId: 'com.example.kfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMjfLwdlgM0C5LS22gV_7rVuOpaTXf6aI',
    appId: '1:774583050669:ios:11887cb33c330edc368124',
    messagingSenderId: '774583050669',
    projectId: 'food-ap-2eeb8',
    storageBucket: 'food-ap-2eeb8.firebasestorage.app',
    iosBundleId: 'com.example.kfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaeIkmBy5t2rZHag8tmWwrrUCv0rf4LLM',
    appId: '1:774583050669:web:d8b235a39be240fb368124',
    messagingSenderId: '774583050669',
    projectId: 'food-ap-2eeb8',
    authDomain: 'food-ap-2eeb8.firebaseapp.com',
    storageBucket: 'food-ap-2eeb8.firebasestorage.app',
    measurementId: 'G-6D6XWYBEEP',
  );

}